
language: android
env:
 global:
 - ANDROID_API_LEVEL=27
 - ANDROID_BUILD_TOOLS=27.0.3
 - ADB_INSTALL_TIMEOUT=5
 - ANDROID_ABI=armeabi-v7a
 - ANDROID_TAG=google_apis
 - QEMU_AUDIO_DRV=none
 
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_LEVEL
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMULATOR_LEVEL
    
 licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  
  sudo: required

jdk:
  - oraclejdk8

install: true

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
  
script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
  
 before_script:
  - chmod +x gradlew
  
 script:
  - ./gradlew assembleDebug --stacktrace
  
 deploy:
  provider: releases
  api-key: $GITHUB_APIKEY
  file: "app/build/outputs/apk/app-debug.apk"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
