language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - build-tools-3.1.2
    - android-27
    - build-tools-26.0.2
    - android-27
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - sys-img-armeabi-v7a-android-27
    - sys-img-armeabi-v7a-android-17
    
    licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
